### ISSUE TITLE
CSS custom properties not properly compiled

### ISSUE THREAD

**Issue by ohkimur** [BuilderIO/mitosis#1107]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [X] Angular
- [X] HTML
- [X] Qwik
- [X] React
- [X] React-Native
- [ ] Solid
- [X] Stencil
- [X] Svelte
- [X] Vue
- [X] Web components

### Reproduction case

[link](https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNrrgXzgDMoIQ4ByAAQCNlgAbAE3SgDpgIB6EYHVYKgoBuAFCj0AD0iw4LIgENkDeEWQA7AMYxO6uAFkAngGEykdenUwAFGFJhUASkSi4cKOhjIoe667dwADxMwABu%2FgFwmqioALwICBGRlAC0KTDoqDApmhAM0BQAXJQ0DMjoFAA0SZG5%2BVDFFKEKUNZpGVk5edCV7uhMjlU1BPhJAHyBXCGhY%2F6OYqNAA%3D)

### Expected Behaviour

The CSS from an element that contains a custom property (CSS variable) like below:

```jsx
<div css={{
  '--test-color': 'blue',
  color: "var(--test-color, red)",
}}></div>
```

should compile to valid CSS like in the following example:

```html
<style>
  .div {
    --test-color: blue;
    color: var(--test-color, red);
  }
</style>
```

### Actual Behaviour

The CSS from an element that contains a custom property (CSS variable) like below:

```jsx
<div css={{
  '--test-color': 'blue',
  color: "var(--test-color, red)",
}}></div>
```

compiles to the following (the `--` part from the CSS custom property is omitted):

```html
<style>
  .div {
    test-color: blue;
    color: var(--test-color, red);
  }
</style>
```

**Comment by samijaber** [comment]
Thanks for filing!

The bug is here:

https://github.com/BuilderIO/mitosis/blob/26a4f4ffdaef0f0001038ed5adbb7f0669a832e8/packages/core/src/helpers/styles/helpers.ts#L94

`dashCase` calls lodash's `kebabCase`, which strips the initial `--` prefix. We need to add some logic that will preserve `--` if it is at the beginning of the string

**Comment by samijaber** [comment]
@ohkimur that would be great! Just to make sure this is what you plan on doing:

- please create individual issues for each bug first (in case there is context I need to provide around edge cases/circumstances)
- raise individual PRs instead of PRs that fix many issues in one go

But yeah, I highly welcome you coming in and helping improve Mitosis in any way! 🙏🏽

**Comment by ohkimur** [comment]
@samijaber I found a very annoying bug with the CLI. The CLI doesn't seem to work with custom configuration files. I found the problem and I already fixed it on my local clone. I'll make a PR just with that. Do you also need an issue for that, or is enough if I write what I fix in the PR?

**Comment by ohkimur** [comment]
@samijaber I made a PR for the CLI issue.
