### ISSUE TITLE
Support for JSX output in Vue

### ISSUE THREAD

**Issue by wabi-habi** [BuilderIO/mitosis#1234]
### I am interested in helping provide a feature!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [X] Vue
- [ ] Web components

### What problem does this feature solve?

How does vue compile to jsx?

### What does the proposed API look like?

How does vue compile to jsx?

**Comment by kingzez** [comment]
Not support yet,  we discussed before https://github.com/BuilderIO/mitosis/discussions/1021

**Comment by wabi-habi** [comment]
This is really necessary, as many components are completely unwieldy without jsx functionality

**Comment by samijaber** [comment]
As @kingzez mentioned, this is not supported yet. It is not a high-priority thing to do, because the syntax of the Mitosis output does not matter. It is a build artifact that developers don't need to look at. What does matter is:

- Mitosis syntax (for DX)
- performance & external UX of generated output

In this case, as far as I know, adding support for JSX output in Vue does not add any new features or benefits to people who create or consume Mitosis components. It is purely syntactic sugar, so I am not concerned about adding support anytime soon.
