### ISSUE TITLE
Vue2 `For` component not generating `template`

### ISSUE THREAD

**Issue by Marvin-Brouwer** [BuilderIO/mitosis#1332]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [ ] All
- [ ] Angular
- [ ] HTML
- [ ] Preact
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [X] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgMWnAvnAZlCI4BEAAgEYCuwANgCYCmUAdMBAPQjAwQDOwXBA3AChBtAB6RYcOlgCGZSvCxkAdgGMYzZXACyATwDCeSMtrKYACjC4wXAJSJBcOKojKu8MTPCVacALxwANqOToQAjAQANCFOBABMUTGEAMwEIQC6wk5QtDBkUFrmSQA81MAAbgB8SU7F8tWhjXDFqFBwtDKqABZ%2BCJ7etOgNTY0INSNw5hy0IPZ%2BlZPFwxNNxZTAlQjTIOjFLOvLK80slbbjjejnx62HtSz1JSxlVSG2QuhAA%3D

### Expected Behaviour

When switching between Vue2 and Vue3 I'd expect both to have a template or `v-for` output
```html
<template>
  <div>
    <ul>
      <template :key="index" v-for="(item, index) in example">
        <li>{{ item }}</li>
      </template>
    </ul>
  </div>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "my-component",
});
</script>
```

### Actual Behaviour

Vue2 version doesn't have any loop output
```html
<template>
  <div>
    <ul>
      <li>{{ item }}</li>
    </ul>
  </div>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "my-component",
});
</script>
```

### Additional Information

When moving the UL inside of the loop, we get output with a `v-if`, although without a template:
```jsx
<div>
      <For each={example}>
        <ul>
            {
              (item) => (<>
                <li>{item}</li>
              </>)
            }
        </ul>
      </For>
    </div>
```

However, this breaks down in Vue3, and possibly other output formats.

**Comment by samijaber** [comment]
That's because of the extra root fragment you have in there. Remove it and it works:

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgMWnAvnAZlCI4BEAAgEYCuwANgCYCmUAdMBAPQjAwQDOwXBA3AChBtAB6RYcOlgCGZSvCxkAdgGMYzZXACyATwDCeSMtrKYACjC4wXAJSJBcOKojKu8MTPCVacALxwANqOToQAjAQANCFOBABMUTGEAMwEIQC6IVC0MGRQWuZJADzUwABuAHxJTkXyVaENcEWoUHC0MqoAFn4Int606PWNDQjVw3DmHLQg9n4VE0WUwBUIUyDoRSxLFbZjDeh7TSwtQw2bdcUspZUhtkLoQA

The long-term fix is to improve how the Vue2 parser handles For elements: https://github.com/BuilderIO/mitosis/blob/e862056eca675887bd975bf5696c61666d0f3532/packages/core/src/generators/vue/blocks.ts#L68-L98

Unfortunately, that logic is quite hacky due to workarounds concerning Vue2's lack of support for multiple root elements.

Given that Vue2 has reached end-of-life in December, I plan to stop supporting Vue2 generation altogether in Mitosis in the near future

**Comment by Marvin-Brouwer** [comment]
Aha, well the less fragments the better.
I probably added that with trial and error.
Thanks for being so quick on responding!
