### ISSUE TITLE
Samples with SASS

### ISSUE THREAD

**Issue by kmmbvnr** [BuilderIO/mitosis#153]
Hi folks, that  you for very interesting library.

Is there any way to make it works with sass? I'm looking for way to embed css into solid/vue/react/customElement compoments

**Comment by steve8708** [comment]
hey @kmmbvnr - Mitosis has no opinion on this per-se, if you create style sheets in any language you can use the classes in Mitosis components as expected, like [this](https://mitosis.builder.io/?outputTab=vue&code=%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++return+%3Cdiv+class%3D%22my-sass-class%22%3EHello%21%3C%2Fdiv%3E%3B%0A%7D%0A)

```tsx
export default function MyComponent(props) {
  return <div class="my-sass-class">Hello!</div>;
}
```

![image](https://user-images.githubusercontent.com/844291/148273961-2cbcff79-ff23-4dc5-aff1-bd96273ae4a0.png)


You can also use imports like you would when using a bundler like webpack, as since Mitosis is a source to source compiler it just carries the import over to be later processed by other tools

e.g. 

```tsx
import './my-styles.scss'

export default function MyComponent(props) {
  return <div class="my-sass-class">Hello!</div>;
}
```

becomes

```vue
<template>
  <div class="my-sass-class">Hello!</div>
</template>
<script>
import {} from "./my-styles.scss";

export default {
  name: "my-component",
};
</script>
```

etc

You can see that in action [here](https://mitosis.builder.io/?outputTab=vue&code=import+%27.%2Fmy-styles.scss%27%0A%0Aexport+default+function+MyComponent%28props%29+%7B%0A++return+%3Cdiv+class%3D%22my-sass-class%22%3EHello%21%3C%2Fdiv%3E%3B%0A%7D%0A)

![image](https://user-images.githubusercontent.com/844291/148274109-0ec946d2-2df4-42e5-b55c-909ed060269b.png)

If this workflow doesn't fit your use case well though happy to hear more about why and we can think on longer term solutions

**Comment by samijaber** [comment]
Closing as this seems resolved/answered.

**Comment by PatrickJS** [comment]
We ran into this too. If you plan on working within multiple frameworks you're forced to not use any features a framework might have to encapsulate styles. You must rely on your build system to do so (generate scoped styles).

**Comment by JSMike** [comment]
@PatrickJS Is it possible to use (s)css modules to mangle the classes during build time?

**Comment by samijaber** [comment]
@JSMike Yeah, that is definitely possible to do by adding the necessary SCSS build tools for each output.
