### ISSUE TITLE
Mitosis => Angular:  Duplicated props

### ISSUE THREAD

**Issue by alujs** [BuilderIO/mitosis#260]
The variable `name` is declared once as an Input and then again as a class variable. 

Add any other context about the problem here.](https://mitosis.builder.io/?outputTab=angular&code=import+%7B+useState%2C+onMount+%7D+from+%27%40builder.io%2Fmitosis%27%3B%0A%0Aexport+default+function+ThrowAwayButton%28props%29+%7B%0A++const+state+%3D+useState%28%7B+name%3A+%22%22+%7D%29%3B%0A%0A++onMount%28%28%29+%3D%3E+%7B%0A++++state.name+%3D+props.name+%3F+props.name+%3A+%27Default%27%3B%0A++%7D%29%3B%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++Hello+from%0A++++++%3Cspan%3E+%7Bname%7D%3C%2Fspan%3E%0A++++++%21%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D%0A)

**Comment by samijaber** [comment]
Isn't that because you have both a prop and a state with the same name? To illustrate, here's the output if you name them differently: [fiddle](https://mitosis.builder.io/?outputTab=angular&code=import+%7B+useState%2C+onMount+%7D+from+%27%40builder.io%2Fmitosis%27%3B%0A%0Aexport+default+function+ThrowAwayButton%28props%29+%7B%0A++const+state+%3D+useState%28%7B+nameInState%3A+%22%22+%7D%29%3B%0A%0A++onMount%28%28%29+%3D%3E+%7B%0A++++state.nameInState+%3D+props.name+%3F+props.name+%3A+%27Default%27%3B%0A++%7D%29%3B%0A%0A++return+%28%0A++++%3Cdiv%3E%0A++++++Hello+from%0A++++++%3Cspan%3E+%7Bstate.nameInState%7D%3C%2Fspan%3E%0A++++++%21%0A++++%3C%2Fdiv%3E%0A++%29%3B%0A%7D%0A)

Also note that you have a bug in your JSX: you reference `name` without prefixing it with `state.`  nor `props.`

**Comment by alujs** [comment]
You're right, this should be handled by the linter, closing this.
