### ISSUE TITLE
Support multiple children props

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/mitosis#275]
There is currently no way to support multiple children, as in this example from the React docs: https://reactjs.org/docs/composition-vs-inheritance.html

```jsx
function Dialog(props) {
  return (
    <FancyBorder color="blue">
      <h1 className="Dialog-title">
        {props.title}
      </h1>
      <p className="Dialog-message">
        {props.message}
      </p>
    </FancyBorder>
  );
}

function WelcomeDialog() {
  return (
    <Dialog
      title="Welcome"
      message="Thank you for visiting our spacecraft!" />
  );
}
```

[fiddle link](https://mitosis.builder.io/?outputTab=vue&code=export+default+function+MyComponent%28props%29+%7B%0A++return+%28%0A++++%3CFancyBorder+color%3D%22blue%22%3E%0A++++++%3Ch1+className%3D%22Dialog-title%22%3E%0A++++++++%7Bprops.title%7D%0A++++++%3C%2Fh1%3E%0A++++++%3Cp+className%3D%22Dialog-message%22%3E%0A++++++++%7Bprops.message%7D%0A++++++%3C%2Fp%3E%0A++++%3C%2FFancyBorder%3E%0A++%29%3B%0A%7D)

This fiddle does output the correct code for React, but almost all other frameworks need explicit new logic to handle multiple slots/pieces of content.

**Comment by steve8708** [comment]
I think to support this we will need to have a first class feature in Mitosis around Slots. Since React is more flexible as to what you can do compared to other frameworks, we'll need to design an implementation in Mitosis that is easy to use and can support all of our output targets, even the most constraining of them. tmk `slot`, like used in most non-react frameworks, is the most common convention and is the most consistent across

may be a good one to do an RFC for
