### ISSUE TITLE
Different results with CLI or with mitosis.config.js

### ISSUE THREAD

**Issue by CKGrafico** [BuilderIO/mitosis#381]
Hello,
For sure I'm doing something wrong but I'm having different results using `mitosis.config.js` than the cli.

```
module.exports = {
  files: 'src/**/*.lite.tsx',
  dest: 'packages',
  options: {},
  targets: ['react', 'html', 'angular']
};

```

This generates compiled JS files not components.

but using commands like:
```
mitosis compile --to=react src/button/button.lite.tsx > packages/react/src/button/button.lite.jsx
```

Generates the expected component.
I'was digging into the docs and config options but I cannot find how to using the config file I can have the same result, I don't need the code compiled I'm good with just the components.

Sorry for not understanding this, if not possible no problem I'll use the CLI commands into npm scripts and done

**Comment by CKGrafico** [comment]
Meanwhile I did that horrible script :D but maybe it works to someone like me.

```
const glob = require('glob');
const filesystemTools = require('gluegun/filesystem');
const stringTools = require('gluegun/strings');
const printTools = require('gluegun/print');
const config = require('./mitosis.config');
const compileCommand = require('@builder.io/mitosis-cli/dist/commands/compile');

function compile(filename) {
  config.targets.forEach((target, i) => {
    compileCommand.run({
      parameters: {
        options: {
          from: 'mitosis',
          to: target,
          out: `${config.dest}/${target}/${filename.replace(/\..*/, '')}.${config.extensions[i]}`
        },
        array: [filename]
      },
      strings: stringTools.strings,
      filesystem: filesystemTools.filesystem,
      print: printTools.print
    });
  });
}

glob('src/**/*.lite.tsx', (er, files) => files.forEach((element) => compile(element)));

```

**Comment by PatrickJS** [comment]
I did that too but ended up just using mitosis/core directly which gives you more control over the output

**Comment by CKGrafico** [comment]
Oh thanks! At least I’m not doing the things so wrong that’s nice to know.

**Comment by CKGrafico** [comment]
My thing was that I wanted to manage the transpilation by myself, right now what I'm doing the transpilation to components using mitosis like this https://github.com/CKGrafico/papanasi/blob/main/mitosis.compiler.js (not so clean I know) and the transpilation to esm and umd with lerna and rollup like this  https://github.com/CKGrafico/papanasi/blob/main/rollup.config.js and https://github.com/CKGrafico/papanasi/blob/main/packages/react/rollup.config.js

**Comment by samijaber** [comment]
One thing I noticed: `mitosis build` and `mitosis compile` are different commands that do different things:
- `mitosis compile` is a much simpler command: it takes 1 file and outputs it to one target.
- `mitosis build` will handle an entire directory, which may include non-mitosis JS/TS files etc.

You have been interchanging the two, so I believe that's where the discrepancy lies. Looking at https://github.com/CKGrafico/papanasi/commit/722b96790711c559eac73d5ce484dd2d89c4d841#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L8, you were using `mitosis build`, but in this issue, you're comparing its output to that of `mitosis compile`. So the issue is not CLI vs `mitosis.config.js`, it's `build` vs `compile`.

> My thing was that I wanted to manage the transpilation by myself

Yup, I hear you! That's exactly what we've realized as well while generating react-native code. We're open to remove the transpile step I linked to in the previous comment, and leaving that off to the end-user. Alternatively, we can move it behind a `shouldTranspileComponent: boolean` flag for react/react-native configurations.

**Comment by CKGrafico** [comment]
Hello @samijaber the "non- transformation" is happening everywhere as you can easily check in the builder.
![image](https://user-images.githubusercontent.com/2048511/170632719-36d3a948-8b9d-4119-a0a7-374e1916375a.png)

The only difference is that seems that in angular is the only one where you are taking all the html and wrapping in a string.
![image](https://user-images.githubusercontent.com/2048511/170632838-8c97dd0b-9b0b-4003-8f72-25cda99346a2.png)

**Comment by ixTec** [comment]
@samijaber Was there any followup to your previous comment? Having the `shouldTranspileComponent` boolean or similar is what's blocking our team from using Mitosis right now, as we don't want to transpile the react components originally
