### ISSUE TITLE
core: allow destructure assignment of state and props

### ISSUE THREAD

**Issue by PatrickJS** [BuilderIO/mitosis#389]
we should undo the destructure assignment so the rest of the code generators still work. In some parts of the generators we are relying on props. or state.

**Comment by samijaber** [comment]
> we should undo the destructure assignment

What do you mean by that exactly? Which de-structure assignment?

**Comment by PatrickJS** [comment]
react developers do de-structure assignments all the time for props. A lot of the generator code relies on `props.` so it would be better to undo their de-structured props

```jsx
function MyComponent({children}) {

  return (
    <div>
      {children}
    <div>
  )
}
```
convert it to props before the generator runs

```jsx
function MyComponent(props) {

  return (
    <div>
      {props.children}
    <div>
  )
}
```

**Comment by samijaber** [comment]
Oh I see. You're saying that the JSX Parser should include logic that, if `props` or `state` is de-structured, then it should be smart enough to swap the restructure with `props`/`state`, and the assignments/uses of the variables with `props.children` and `state.foo` so that the Mitosis syntax is still able to rely on de-structuring for better dev UX.

Yeah, that would be neat and not a particularly difficult thing to implement either!

**Comment by PatrickJS** [comment]
💯 Yeah that would be great

**Comment by decadef20** [comment]
the de-structured assignment may do alias or set a default value. If we undo it,  we need to handle the default value of props

```js
export default function MyComponent({children: c, type, color = 'blue'}) {

  return (
    <div>
      {c}
      Hello! I can run in React, Vue, Solid, or Liquid!
    </div>
  );
}
```

**Comment by samijaber** [comment]
Closing as I believe #468 implemented this!
