### ISSUE TITLE
[Discussion] Different outputs in cli and online fiddle

### ISSUE THREAD

**Issue by pro-nav** [BuilderIO/mitosis#418]
First of all great tool you have. Thanks.

I am using `mitosis` to compile my react code to vanilla html. I am getting different html results from the `cli` tool and the hosted app at `mitosis.builder.io`. I actually prefer the code generated by the online fiddle and want to know what version/commit is being served online and is there a way to use the same locally?

By preferred code I want code to compile to 
```html
 <span data-name="show">
    <div className="model" data-name="div-1">
      <p>MyApp</p>
      <button className="btn-go" data-name="button-1">Connect</button>
    </div>
  </span>

/* from online fiddle */
```  
instead of using templates as in
```html
  <template data-name="show">
    <div className="model" data-name="div-1">
      <p>MyApp</p>

      <button className="btn-go" data-name="button-1">
        Connect
      </button>
    </div>
  </template>

/* from cli tool and locally hosted fiddle */ 
```

**Comment by PatrickJS** [comment]
Yeah the original code had a lot of problems. Ideally we can both defending on the edge case. In the original one a root element is required but because of accessibility we can't have span tags within  ul and li. The other issue was that you're forced to style around the span tags. If you compile to react and webcomponent the view can look different because of that small difference. I want to detective that there's one child node and use that as the host element in the future. A lot of problems were due to the original binding code which requires another refactor.

**Comment by samijaber** [comment]
> what version/commit is being served online

That was an old version. We just deployed the latest Mitosis version to the fiddle, so they should at least be consistent.

@PatrickJS's explanation covers why those changes happened (a11y and removing redundant `span` tags)

**Comment by samijaber** [comment]
Closing as I think this is resolved (fiddle is now constantly using latest version of mitosis)
