### ISSUE TITLE
Svelte generation fails if there is an inner function

### ISSUE THREAD

**Issue by kylecordes** [BuilderIO/mitosis#472]
- [X] I am interested in helping provide a fix!

**Scope**
- [X] This only impacts specific generators/outputs (please list them here): Svelte

**Describe the bug**

Mitosis fails with an error trying to generate Svelte output for a simple component with an inner function, in this case addItem()

```
import { useState } from '@builder.io/mitosis';

export interface State {
  list: string[];
  newItemName: string;
}

export default function MyComponent(props: any) {
  const state = useState<State>({
    list: ['hello', 'world'],
    newItemName: 'New item',
  });

  function addItem() {
    state.list = [...state.list, state.newItemName];
  }

  return (
    <div
      css={{
        padding: '10px',
      }}
    >
      <link
        href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
        rel="stylesheet"
      />

      <input
        class="shadow-md rounded w-full px-4 py-2"
        value={state.newItemName}
        onChange={(event) => (state.newItemName = event.target.value)}
      />

      <button
        class="bg-blue-500 rounded w-full text-white font-bold py-2 px-4"
        css={{
          margin: '10px 0',
        }}
        onClick={(event) => addItem()}
      >
        Add list item
      </button>

      <ul class="shadow-md rounded">
        {state.list.map((item) => (
          <li
            class="border-gray-200 border-b"
            css={{
              padding: '10px',
            }}
          >
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}
``

**To Reproduce**

Checkout current mainline.

Edit ``packages/e2e-app/mitosis.config.js` to un-comment svelte output

`yarn workspace @builder.io/e2e-app run build`

Notably, if you remove the inner addItem function, Svelte output is generated.

**Expected behavior**

Generates (valid) Svelte

Alternatively, maybe such an inner function is considered invalid Mitosis? It work OK for React, Solid, Vue (at least)

**Comment by samijaber** [comment]
Oh, I would move `addItem` as a function within `state`. In mitosis, any constant, variable or function you want needs to exist within `state`. You should not expect a "loose" function like this in the component scope to work properly

**Comment by samijaber** [comment]
I'm not surprised this worked in React, but I'd expect it to start breaking in other targets sooner!

**Comment by kylecordes** [comment]
Ideas:

* Detect and emit error message when parsing, rather than fail in generating
* Enhance docs about how you are intended to code in Mitosis

Are there any docs for this? I am happy to PR an improvement with the thing you described above.

**Comment by samijaber** [comment]
Yeah, in general, we have tried to document everything in https://github.com/BuilderIO/mitosis/blob/main/docs/gotchas.md, or even codifying it in ESLint rules that error if you attempt to do something that won't work as expected: https://github.com/BuilderIO/mitosis/tree/main/packages/eslint-plugin

The reason I might not want to codify what I said in this issue is that technically, this should work. I was mostly pointing out a way that will more reliably work if you run into issues.


## More context on State management

Today, you have to use one of two formats, either react style:

```tsx
const [foo, setFoo] = useState(null)
function addItem() { ... }
```

OR

```ts
const state = useState({ /* everything here */ })
```

We don't yet fully support mixing and matching those approaches together, but that could be done. In theory, all we need to do is make a change here:

https://github.com/BuilderIO/mitosis/blob/590b9c5e873bf92465dbdd5e0e3d57d818e6724a/packages/core/src/parsers/jsx.ts#L347

So that instead of overwriting the `state` of a MItosis JSON altogether when we see `const state = useState()`, we combine it with the other state we've collected:

```ts
Object.assign(state, parseStateObject(firstArg));
```


## Svelte bug

However, there might be a svelte-specific issue here you're noticing in this PR. I'm not sure what the error is, but regardless of what I described in this comment, we might have to fix a bug in how Svelte handles state functions or functions in general 🤔

**Comment by kylecordes** [comment]
I think we can close this one because the ongoing improvement of the docs to set expectations of what code works is already well-known elsewhere, right?

**Comment by samijaber** [comment]
I'd rather stick with creating issues until we have that system in place, to avoid the risk of forgetting what to test for. I don't mind having tons of issues highlighting bugs 😄
