### ISSUE TITLE
Dynamic component not supported

### ISSUE THREAD

**Issue by florian-lefebvre** [BuilderIO/mitosis#587]
### I am interested in helping provide a fix!

No

### Which generators are impacted?

- [X] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnACrADOMAwhALaR7B4wAUYUEY1AlHADeAKDhwCZWnACimYIzbwAvHG69qAOlTU4AHz1wARACN0MGGSMBuMXCjAY6KOQA8chUrgB6AHwiAXyA%3D%3D%3D

### Expected Behaviour

The component should be dynamic. For instance on React:
```tsx
export default function TestComponent(props) {
  const Element = props.as || "button";
  return <Element />
}
```

### Actual Behaviour

It only return `Element` without taking into account the fact that it is dynamic.

### Additional Information

Would be great if such types (see links below) could be supported.

- https://github.com/sideelec/sideelec.com/blob/main/types/polymorphic.ts
- https://github.com/sideelec/sideelec.com/blob/main/components/Button.tsx

**Comment by samijaber** [comment]
Dynamic components are well supported. Your example breaks because you are declaring a constant in the render body, which Mitosis does not handle well. See [this example](https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNroL5wBmUEIcA5AAIBGywANgCbpQB0wEA9CMDqsKnIAoIegAekWHGaEAhsnrxCyAHYBjGBxVwAKulQwAwqUgr0KmAAowJMKgCUiIXDhqIKg3AOyY6OAF4UDGxcSwRnFzgAc3R4dHp0EHMYADlZJMtHcMjIqFjkKG0bCDtWWVQ4AB9KiloYHBVhHLwIvHsIvJgC7QAeb19WeMTktKS4TgA%2BITwgA) of how your code should be written instead.

We have an ESLint rule highlighting that you can't declare naked variables in the component: https://github.com/BuilderIO/mitosis/blob/main/packages/eslint-plugin/docs/rules/no-var-declaration-or-assignment-in-component.md, but we might benefit from improving our docs to include a section on "how to write a Mitosis component"!
