### ISSUE TITLE
Would it be possible to use mitosis with nodegui?

### ISSUE THREAD

**Issue by codehangen** [BuilderIO/mitosis#718]
Hi all! 

Mitosis has a series of compatible frameworks like react, vuejs etc. It is possible with mitosis to generate codes from these frameworks I mentioned. In that sense, I would like to create my desktop apps with mitosis through nodegui. So... would it be possible to use mitosis with nodegui?

**Comment by samijaber** [comment]
I don't know much about NodeGUI. But since it has [React](https://react.nodegui.org/), [Vue](https://vue.nodegui.org/) and [Svelte](https://svelte.nodegui.org/) versions, you should be able to generate React/Vue/Svelte components in Mitosis, and then import them into your NodeGUI project without any issues
