### ISSUE TITLE
Preserve types in generated state/hooks code

### ISSUE THREAD

**Issue by kingzez** [BuilderIO/mitosis#909]
### I am interested in helping provide a fix!

Yes

### Which generators are impacted?

- [X] All
- [ ] Angular
- [ ] HTML
- [ ] Qwik
- [ ] React
- [ ] React-Native
- [ ] Solid
- [ ] Stencil
- [ ] Svelte
- [ ] Vue
- [ ] Web components

### Reproduction case

https://mitosis.builder.io/?outputTab=E4UwhgxgLkA%3D&code=JYWwDg9gTgLgBAbzgVwM4FMDKNrrgXzgDMoIQ4ByAAQCNlgAbAE3SgDpgIB6EYHVYKgoAoYcAB2MVkQCGAYzwAVGQHMACqTCpEwuHDkQG0AFxxUMKBJXD8o9AA9IsOC1nIG8IsnFyYncXDKKgAUYJqopkEaEFoAlDp6BuLmZjAyUnAAvCgY2LjBCKJ6eiro8KUwAMIMqMGxpuaW4ioJxYkQyfAGRlAASugGUEym%2FYNMADyNVgA0qU0qAHxZrW16YaAyUACephQAxADMcgBs6EQADBTTuqt6qMhyCqgRlHsAjABMNAcArExXN1uAHdNuIrLs9kwPgBOc5wgG3PRMGTNVgQohyA4AdmxCNWtkBxSgZWQUAC3Wgo2gTAA2mEYqg2BSoABdOAAH3ZlFcMncMBEbXw10JAAsUUwGOhqhAMMF0AA3dCSUwAWQgaHQAFFFZJ4oVBdc9PhYkU4MSYKSAsFxkxgPL9AwZM9MghzOl0GwKtVUIQOtVgHIANYuuU6%2BCZJZuqRsMXiCVSoyyhVKmCxWL4BbjLi2%2BULE22IA%3D

### Expected Behaviour

should preserve types: `string`, ` Record<string, string>`, `MouseEvent`

react 
```ts
import * as React from "react";

export default function Tag(props: Props) {
  function getCls(): string {
    const colorRecord: Record<string, string> = {
      primary: "#3c6ef0",
      success: "#12b35d",
      warning: "#d29000",
      danger: "#fc3737",
    };
    return colorRecord[props.color] || "default";
  }

  function handleClose(event: MouseEvent) {}

  return <div className={getCls()} onClick={(event) => handleClose(event)} />;
}

```

vue

```ts
<template>
  <div :class="_classStringToObject(getCls)" @click="handleClose($event)"></div>
</template>

<script lang="ts">
interface TagProps {
  color: string;
}

export default {
  name: "tag",

  props: ["color"],

  computed: {
    getCls(): string {
      const colorRecord: Record<string, string> = {
        primary: "#3c6ef0",
        success: "#12b35d",
        warning: "#d29000",
        danger: "#fc3737",
      };
      return colorRecord[this.color] || "default";
    },
  },

  methods: {
    handleClose(event: MouseEvent) {},
    _classStringToObject(str) {
      const obj = {};
      if (typeof str !== "string") {
        return obj;
      }
      const classNames = str.trim().split(/\s+/);
      for (const name of classNames) {
        obj[name] = true;
      }
      return obj;
    },
  },
};
</script>

```

### Actual Behaviour

does not preserve types: `string`, ` Record<string, string>`, `MouseEvent`

react 
```ts
import * as React from "react";

export default function Tag(props) {
  function getCls() {
    const colorRecord = {
      primary: "#3c6ef0",
      success: "#12b35d",
      warning: "#d29000",
      danger: "#fc3737",
    };
    return colorRecord[props.color] || "default";
  }

  function handleClose(event) {}

  return <div className={getCls()} onClick={(event) => handleClose(event)} />;
}

```

vue

```ts
<template>
  <div :class="_classStringToObject(getCls)" @click="handleClose($event)"></div>
</template>

<script lang="ts">
interface TagProps {
  color: string;
}

export default {
  name: "tag",

  props: ["color"],

  computed: {
    getCls() {
      const colorRecord = {
        primary: "#3c6ef0",
        success: "#12b35d",
        warning: "#d29000",
        danger: "#fc3737",
      };
      return colorRecord[this.color] || "default";
    },
  },

  methods: {
    handleClose(event) {},
    _classStringToObject(str) {
      const obj = {};
      if (typeof str !== "string") {
        return obj;
      }
      const classNames = str.trim().split(/\s+/);
      for (const name of classNames) {
        obj[name] = true;
      }
      return obj;
    },
  },
};
</script>

```

**Comment by samijaber** [comment]
The JSX Parser is actually storing all of these types correctly in the Mitosis Component JSON.

The issue is that all generators rely on the Babel `babel.transform()` to transform code chunks (remove/manipulate references to `state.` and `props.`, etc.) here:

https://github.com/BuilderIO/mitosis/blob/f68fc5b5dedf8fc42fb27d558959e4076702c1f8/packages/core/src/helpers/babel-transform.ts#L49

This function is called by all generators, for code that lives within `useState`, `useStore`, and all other hooks. Unfortunately, `babel.transform()` will also strip away types. 😕

I do not have an immediate solution to this. But what needs to happen is either:

- find a way to use `babel.transform()` without stripping TS types away. This does not seem to be possible from my research. See [this babel REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=ATDGHsDsGcBdjgQ1gU2AXmAV2igyrOAE4oAUA3gFAggDmK89sAwgDbSkCUAXArEQEtItYFRo0IMeBFbEASighEAJrwVLlAHjiDhAGj67aAPgyjq4mgAdBAW0REAnrwDkAYgDMoAGwoAZgAMLnoWlghYoKAo0NCubgCMAEwARh4ArMrBoZYA7g6QQrRxyokAnAEVWWEgyojCKERxfqAeAOxtVZYAvpTZICSwWESQYOCyROrEygDaNuBW0AB0MsQAusAAPhvALsr-iFissC7ZXSHZABZ1yqwobOC4pCgAbiiQsLwAsuA4KACir3enHMYUk0DGKEWsloT0BsE4pxCIC6CKAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.20.6&externalPlugins=&assumptions=%7B%7D).
- replace `babel.transform()` with another AST transformation tool, like the TypeScript AST. See [this guide](https://github.com/itsdouges/typescript-transformer-handbook).


It seems like the second option is most likely what we'll need to do. This might be a big/hairy refactor 😅...

**Comment by kingzez** [comment]
Still not work, this is https://github.com/BuilderIO/mitosis/blob/main/packages/core/src/__tests__/data/blocks/columns.raw.tsx


https://mitosis.builder.io/?outputTab=G4VwpkA%3D&code=PTAEAsBdIBwZwFwgOYEtLgK4CMB0BjAewFtgAhTVAGwBMBTAJwEkB5YY9QuVOYbKwtnYBDVADtgMYfgDWw5HV5EGdYHAb5gAfS2RFkODuA1hkYXwGylhKpmJi4uBsIDuuAwA8AUF9TEYhAyQoADeoJhwdADKkIF0ADSgAGKBoAC%2BoABmDCSgAOQAAtiUtIy4qITsnNxweQDcPpAAnjB0oADCNnZioAC8oV6goERieqMIoMJiTQ1DIKAAKiwAIiwTTP5UdMR0o6AYPKAu4LugcJgwAUFZqTRNYsIc%2BB1RUaBUUzRwg0eoNBgAfgmYjs2EYDTSDS8dA8V2C4j0DEy0janVs9gACjl4AMhkR0Q4gR0uvYANoAXShczAS1W602212wQOcCOJx650ugWCmVu90eqGe7Ve70%2B3yGcCk%2BDoRJBxDBDFmoHmtLWoA2MC2Oz2LLZp05cJuDFAdweTxebw%2BYi%2BPzgZlkaO6cAAgpAiXkzPw6JA8qAAD75YiCah0X0BvJiOgAN0Y9R%2BKpWao1WqZ%2B3Ah2O%2Bouht5xtNAqFIqtNqGKhjDEijvscAA6uyYtIZHQaETsIQbHQphCfDDDfRkZgqDzMGJ8JAKj0q2IABQwbGIYkErGEeAASlxw0IDmCdtMbX6EWisRU05CPyGCkgU7g09XEynFI3Q1L3swDB6c5XjnxTv9AYpSpDGk8TnqAl4AOKYNAjBRKgABedC3sCoKME%2Bz4qJAb49M0rSEJkoCfvAuCSiifS9P0EYoQwvoAgR87EVKbR%2BgGAAMoATAATCxgHpCBz5gd6NZ%2FBg07iPQHjIfKjDrme%2FF4ludqbgSrL9Luei4Je163jxL6Ye%2BoDTj%2B1akmJMLkqAABkFlKU6JnWmZuAuMJ4DrsxoAAIwsWxYBGQ4uBbGIyAYDxwGgZpJJiO0cC1s5on2RJoBygqMmgfJ242dWfRnGY6nhcp2mpZu6XIFBiKwQhWVqXQGnepB0EMOViGrjpRWKec2CQM4Y5Cf84BZdOJX1Y1oAAFQGb5jgBUFfUALQeau64%2BRFk27NNLUYVhoAAAb4MIVD4NOAAkIRVTVkA9SJpkeKuaQAKSgHNx3tZ10jnc5aQwNdW0hXx6TNT4umbdOoEADw0KgUaFfgHzRb0ABExTUPQDAzRNcNQ7DISyXJQzg5KHxNBMeSZFsHh5L9OMkzCyyoCoY4TkTvnk4VQx7agyBiEwejEAueR2hh%2BDgMzONDFQ4h0AAEnQ7NQETYiBMQe3CyLhQ7ODwgGYrHgzU5vUTAAnIbn2rnkEzYyLWSkzTdPjluRM5C4ys46FFuq82qAa9OWs685EwAGwAMz68bptoZTVu03Q9N2%2FkDszWWjCRE7ckuynaSgQAfIVIMpManaC70ISEd%2By1pFnFshIZEWJFd669BnBks8%2BYMQ8MMNwPDiOlCjvlw8MmNhFTHjgQ7RPub6aRl03%2FEhL5BBbmMkAZCEV3pxbQwg8YEPlyLN3Z8Auc7xvW9Rjv%2F3p0AA%3D

**Comment by samijaber** [comment]
This does work, but we have a bug in the Fiddle where the `typescript` option wasn't being respected. Fixing in https://github.com/BuilderIO/mitosis/pull/1110

**Comment by kingzez** [comment]
I  have some confused about this

raw file : https://github.com/BuilderIO/mitosis/blob/main/packages/core/src/__tests__/data/blocks/columns.raw.tsx#L25

```tsx
const state = useStore({
  getColumns(): Column[] {
    return props.columns || [];
  },
  getGutterSize(): number {
    return typeof props.space === 'number' ? props.space || 0 : 20;
  },
```

snapshot: https://github.com/BuilderIO/mitosis/pull/1085/files#diff-5c26547ec6bd2e4158291b871805f8465adcd4f2ffdd69227d4f028e643737a7L3770

```js
methods: {
  getColumns() { // here should has type Column[]
    return this.columns || [];
  },
  getGutterSize() { // here should has type number
    return typeof this.space === \\"number\\" ? this.space || 0 : 20;
  },
```

**Comment by kingzez** [comment]
Okay, thanks for your answer.
